version: "3"
services:
  lyrics_db:
    image: arangodb:3.7
    ports:
      - 8529:8529
    volumes:
      - arango_data:/var/lib/arangodb3
      - arango_apps_data:/var/lib/arangodb3-apps
    environment:
      ARANGO_ROOT_PASSWORD: password

volumes:
  arango_data:
  arango_apps_data: